CREATE TABLE TB_CLIENTES (
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    ENDERECO1 VARCHAR2(150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR2(1),
    LIMITE_CREDITO NUMBER(15,2),
    VOLUME_COMPRA NUMBER,
    PRIMEIRA_COMPRA NUMBER(1)
);
        
CREATE TABLE TB_VENDEDORES (
     MATRICULA VARCHAR2(5),
     NOME VARCHAR2(100),
     DATA_ADMISSAO DATE,
     PERCENTUAL_COMISSAO NUMBER
);

CREATE TABLE TB_PRODUTOS (
    PRODUTO VARCHAR2(20),
    NOME VARCHAR2(150),
    EMBALAGEM VARCHAR2(50),
    TAMANHO VARCHAR2(50),
    SABOR VARCHAR2(50),
    PRECO_LISTA NUMBER
);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES 
('1040107', 'Light - 350 ml - Melância', 'Lata', '350ml', 'Melância', 4.56);

SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES
('00233', 'João Geraldo Fonseca', TO_DATE('01-12-2015', 'DD-MM-YYYY'), 0.10);

INSERT INTO TB_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES
('00400', 'Maria do Rosario', TO_DATE('23-07-2012', 'DD-MM-YYYY'), 0.15);

INSERT INTO TB_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES
('00810', 'Marcia Almeida', TO_DATE('14-12-2016', 'DD-MM-YYYY'), 0.18);

INSERT INTO TB_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES
('00414', 'Carlos Moreira', TO_DATE('13-11-2015', 'DD-MM-YYYY'), 0.14);

INSERT INTO TB_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES
('00934', 'Juvenildo Martins', TO_DATE('09-03-2010', 'DD-MM-YYYY'), 0.20);

SELECT * FROM TB_VENDEDORES;

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES 
('1037797', 'Clean - 2 litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES 
('1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31);

INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES 
('1004327', 'Videira do Campo - 1,5 Litros - Melância', 'Lata', '1,5 Litros', 'Melância', 19.51);

UPDATE TB_PRODUTOS SET EMBALAGEM = 'Lata' WHERE PRODUTO = '1037797';

SELECT * FROM TB_PRODUTOS;

UPDATE TB_PRODUTOS SET NOME = 'Clean - 350ML - Laranja', TAMANHO = '350 ml', 
PRECO_LISTA = 5.50 WHERE PRODUTO = '1037797'; 

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00233';

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00400';

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00414';

DELETE FROM TB_VENDEDORES WHERE MATRICULA = '00400';

SELECT * FROM TB_VENDEDORES;

ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS PRIMARY KEY (PRODUTO);

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY (MATRICULA);

ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (CPF);

INSERT INTO TB_CLIENTES (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
VALUES
('00333434577', ' João da Silva', 'Rua Projetada numero 10', NULL, 'VILA ROMAN', 'TRÊS RIOS', 'RJ', '22222222',
TO_DATE('12-10-1965', 'DD-MM-YYYY'), 56, 'M', 100000, 2000, 0);